#ifndef COMPONENTS_H
#define COMPONENTS_H

#include <plib.h>

//1 refers to OC1
#define MOTOR_WHEEL_LEFT 1
//OC1
#define MOTOR_WHEEL_LEFT_OC 1
#define MOTOR_WHEEL_LEFT_CONTROL1 LATDbits.LATD5
#define MOTOR_WHEEL_LEFT_CONTROL2 LATDbits.LATD6

#define MOTOR_WHEEL_RIGHT 2
#define MOTOR_WHEEL_RIGHT_OC 2
#define MOTOR_WHEEL_RIGHT_CONTROL1 LATDbits.LATD7
#define MOTOR_WHEEL_RIGHT_CONTROL2 LATDbits.LATD8

#endif