#ifndef COMPONENTS_H
#define COMPONENTS_H

#include <plib.h>

#define MOTOR_WHEEL_LEFT 1
//OC1
#define MOTOR_WHEEL_LEFT_OC1 3
#define MOTOR_WHEEL_LEFT_OC2 4

#define MOTOR_WHEEL_RIGHT 2
#define MOTOR_WHEEL_RIGHT_OC1 1
#define MOTOR_WHEEL_RIGHT_OC2 2

#endif